CREATE USER 'arduino'@'localhost' IDENTIFIED BY 'arduino';
GRANT ALL PRIVILEGES ON *.* TO 'arduino'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'arduino'@'%' IDENTIFIED BY 'arduino';
GRANT ALL PRIVILEGES ON *.* TO 'arduino'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'arduino'@'192.168.1.14' IDENTIFIED BY 'arduino';
GRANT ALL PRIVILEGES ON *.* TO 'arduino'@'192.168.1.14' WITH GRANT OPTION;
FLUSH PRIVILEGES;
exit